CREATE TABLE notice (
  id BIGINT NOT NULL AUTO_INCREMENT,
  sender_id CHAR(10) NOT NULL,
  receiver_id CHAR(10) NOT NULL,
  title VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE todo (
  id BIGINT NOT NULL AUTO_INCREMENT,
  purchase_id BIGINT NOT NULL,
  status ENUM('IN_PROGRESS', 'SUCCESS', 'FAIL') DEFAULT 'IN_PROGRESS' NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE purchase_attachment (
  id BIGINT NOT NULL AUTO_INCREMENT,
  purchase_id BIGINT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  url VARCHAR(2083) NOT NULL,
  summary VARCHAR(100),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE purchase (
  id BIGINT NOT NULL AUTO_INCREMENT,
  sender_id CHAR(10) NOT NULL,
  receiver_id CHAR(10) NOT NULL,
  title VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  price INT NOT NULL DEFAULT 0,
  deadline DATETIME,
  status ENUM('ALIVE', 'CANCELED') DEFAULT 'ALIVE' NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE owner (
  id CHAR(10) NOT NULL,
  email VARCHAR(255),
  password VARCHAR(60),
  google_id VARCHAR(255),
  github_id VARCHAR(255),
  nickname VARCHAR(30) NOT NULL,
  profile_image_url VARCHAR(2083) NOT NULL,
  coins INT NOT NULL DEFAULT 0,
  daily_coins INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

